version: '3.8'

volumes:
    mongo_data: {}

networks:
  front-tier:
  back-tier:

services:
  mongo:
    container_name: monitoring_mongo
    image: mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - back-tier
      - front-tier
